name: CI

on: push 

jobs:
  test:
    strategy:
      matrix:
        target: [test-clj, test-cljs]

    runs-on: ubuntu-latest

    steps:
      - name: Setup CI Environment
        uses: yetanalytics/actions/setup-env@v0

      - name: Run Tests
        run: make ${{ matrix.target }}
